### ISSUE TITLE
Problem with run MyDaoGenerator in AndroidStudio 1.0.1

### ISSUE THREAD

**Issue by Jackly654** [SureCase/GreenDaoForAndroidStudio#2]
When i was fllow http://blog.surecase.eu/using-greendao-with-android-studio-ide/ to Step 5.

I get an exception:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at pl.surecase.eu.MyDaoGenerator.main(MyDaoGenerator.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

------------------------------------------------------------------------
I can not find problem.my project path is :
C:\Users\pengying\AndroidStudioProjects\GreenDaoForAndroidStudio

in MyDaoGenerator build.gradle  outputDir = "../DaoExample/src/main/java-gen"

and fix Error:(7, 0) No such property: outputDir for class: org.gradle.api.internal.project.DefaultProject_Decorated

I have add outputDir="." in gradle.properties.

please help me.THX

**Comment by cafecomcodigo** [comment]
Change:

outputDir = "../____"

to

def outputDir = "../____"

**Comment by ghost** [comment]
Had the same problem. Maybe you should mention that somewhere in the instructions.

**Comment by xenione** [comment]
me too,

**Comment by lwns** [comment]
ME TOO

**Comment by lwns** [comment]
How to solve this problem

**Comment by xenione** [comment]
look at @cafecomcodigo answer

**Comment by arlindiDev** [comment]
Thank you @cafecomcodigo

**Comment by ghost** [comment]
@cafecomcodigo thanks!!!
